name: Build

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/build-tfx.yml"
      - "!LICENSE"
      - "!README.md"
      - "!docs/**"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install
        run: npm install
        working-directory: '${{ github.workspace }}/src'

      - name: Build
        run: npm run build
        working-directory: '${{ github.workspace }}/src'

      - name: Install tfx-cli
        run: npm i -g tfx-cli@0.16.0

      - name: Package (Dev)
        run: >
          tfx extension create
          --root src
          --manifest-globs vss-extension.json
          --output-path $GITHUB_WORKSPACE/builds/dev
          --overrides-file $GITHUB_WORKSPACE/src/overrides.dev.json

      - name: Package (Prod)
        run: >
          tfx extension create
          --root src
          --manifest-globs vss-extension.json
          --output-path $GITHUB_WORKSPACE/builds/prod
          --overrides-file $GITHUB_WORKSPACE/src/overrides.prod.json

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/builds/*
          name: 'task-build-${{ github.run_number }}'
